/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.interestelar;

/**
 *
 * @author viconceicao
 */
public class ProjetoInterestelar extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoInterestelar
     */
    public ProjetoInterestelar() {
        initComponents();
    }
    
    
    private Integer valorTotal = 0;

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTextoPrincipal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblOpcaoUm = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblOpcaoDois = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblOpcaoTres = new javax.swing.JLabel();
        marte = new javax.swing.JButton();
        saturno = new javax.swing.JButton();
        venus = new javax.swing.JButton();
        netuno = new javax.swing.JButton();
        jupiter = new javax.swing.JButton();
        terra = new javax.swing.JButton();
        resetar = new javax.swing.JButton();
        calcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSemDesconto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel1.setText("Planos de viajem Interprise");

        txtTextoPrincipal.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        txtTextoPrincipal.setText("Informe os lugares que deseja viajar!!");

        jLabel2.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel2.setText("Primeiro planeta:");

        lblOpcaoUm.setText("...");

        jLabel4.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel4.setText("Segundo planeta:");

        lblOpcaoDois.setText("...");

        jLabel6.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel6.setText("Terceiro planeta:");

        lblOpcaoTres.setText("...");

        marte.setText("Marte");
        marte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marteActionPerformed(evt);
            }
        });

        saturno.setText("Saturno");
        saturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturnoActionPerformed(evt);
            }
        });

        venus.setText("Vênus");
        venus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venusActionPerformed(evt);
            }
        });

        netuno.setText("Netuno");
        netuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netunoActionPerformed(evt);
            }
        });

        jupiter.setText("Júpiter");
        jupiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupiterActionPerformed(evt);
            }
        });

        terra.setText("Terra");
        terra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terraActionPerformed(evt);
            }
        });

        resetar.setText("C");
        resetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetarActionPerformed(evt);
            }
        });

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        jLabel3.setText("Pacote Triple Eagle da um desconto de 20% o valor da viajem sai por:");

        lblValorTotal.setText("...");

        jLabel7.setText("Sem o desconto:");

        lblSemDesconto.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSemDesconto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(netuno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jupiter))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(marte)
                                            .addComponent(resetar))
                                        .addGap(189, 189, 189)
                                        .addComponent(saturno)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(terra, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(venus, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOpcaoDois))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOpcaoTres))
                            .addComponent(txtTextoPrincipal)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOpcaoUm))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValorTotal)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtTextoPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblOpcaoUm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblOpcaoDois))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblOpcaoTres))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marte)
                    .addComponent(saturno)
                    .addComponent(terra))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venus)
                    .addComponent(jupiter)
                    .addComponent(netuno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcular)
                    .addComponent(resetar))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblValorTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblSemDesconto))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marteActionPerformed

        valorTotal += 2000;
        
        if (lblOpcaoUm.getText().equals("...")) {
            lblOpcaoUm.setText("Marte, uma ótima opção para o mês de Zarcar!! Valor R$ 2000,00");
        }
        else if (lblOpcaoDois.getText().equals("...")){
           lblOpcaoDois.setText("Marte, uma ótima opção para o mês de Zarcar!! Valor R$ 2000,00");
        }
        else if (lblOpcaoTres.getText().equals("...")) {
            lblOpcaoTres.setText("Marte, uma ótima opção para o mês de Zarcar!! Valor R$ 2000,00");
        }
        
        
    }//GEN-LAST:event_marteActionPerformed

    private void saturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturnoActionPerformed
        
        valorTotal += 3500;
        if (lblOpcaoUm.getText().equals("...")) {
            lblOpcaoUm.setText("Saturno, com as melhores praias da galaxia!! Valor R$ 3500,00");
        }
        else if (lblOpcaoDois.getText().equals("...")){
           lblOpcaoDois.setText("Saturno, com as melhores praias da galaxia!! Valor R$ 3500,00");
        }
        else if (lblOpcaoTres.getText().equals("...")) {
            lblOpcaoTres.setText("Saturno, com as melhores praias da galaxia!! Valor R$ 3500,00");
        }
    }//GEN-LAST:event_saturnoActionPerformed

    private void terraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terraActionPerformed
        
        valorTotal += 1500;
        
        if (lblOpcaoUm.getText().equals("...")) {
            lblOpcaoUm.setText("Curta o carvanal da Bahia com as terraquias!! Valor R$ 1500,00");
        }
        else if (lblOpcaoDois.getText().equals("...")){
           lblOpcaoDois.setText("Curta o carvanal da Bahia com as terraquias!! Valor R$ 1500,00");
        }
        else if (lblOpcaoTres.getText().equals("...")) {
            lblOpcaoTres.setText("Curta o carvanal da Bahia com as terraquias!! Valor R$ 1500,00");
        }
    }//GEN-LAST:event_terraActionPerformed

    private void netunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netunoActionPerformed
       
        valorTotal += 3500;
        
        if (lblOpcaoUm.getText().equals("...")) {
            lblOpcaoUm.setText("Netuno, Esclobus por metade do preço!! Valor R$ 3500,00");
        }
        else if (lblOpcaoDois.getText().equals("...")){
           lblOpcaoDois.setText("Netuno, Esclobus por metade do preço!! Valor R$ 3500,00");
        }
        else if (lblOpcaoTres.getText().equals("...")) {
            lblOpcaoTres.setText("Netuno, Esclobus por metade do preço!! Valor R$ 3500,00");
        }
    }//GEN-LAST:event_netunoActionPerformed

    private void jupiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupiterActionPerformed
       
        valorTotal +=1800;
        
        if (lblOpcaoUm.getText().equals("...")) {
            lblOpcaoUm.setText("Júpiter,costeletas de Brugelo de fazer qualquer um salivar! Valor R$ 1800,00");
        }
        else if (lblOpcaoDois.getText().equals("...")){
           lblOpcaoDois.setText("Júpiter,costeletas de Brugelo de fazer qualquer um salivar! Valor R$ 1800,00");
        }
        else if (lblOpcaoTres.getText().equals("...")) {
            lblOpcaoTres.setText("Júpiter,costeletas de Brugelo de fazer qualquer um salivar! Valor R$ 1800,00");
        }
    }//GEN-LAST:event_jupiterActionPerformed

    private void venusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venusActionPerformed
        
        valorTotal += 1300;
        
        if (lblOpcaoUm.getText().equals("...")) {
            lblOpcaoUm.setText("Vênus, Vá a caça de legures com os Venuanos! Valor 1300,00");
        }
        else if (lblOpcaoDois.getText().equals("...")){
           lblOpcaoDois.setText("Vênus, Vá a caça de legures com os Venuanos! Valor 1300,00");
        }
        else if (lblOpcaoTres.getText().equals("...")) {
            lblOpcaoTres.setText("Vênus, Vá a caça de legures com os Venuanos! Valor 1300,00");
        }
    }//GEN-LAST:event_venusActionPerformed

    private void resetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetarActionPerformed
         if (!lblOpcaoTres.getText().equals("...")) {
            lblOpcaoTres.setText("...");
            lblValorTotal.setText("...");
            lblSemDesconto.setText("...");
             lblOpcaoDois.setText("...");
             lblOpcaoUm.setText("...");
            valorTotal = 0;
        }
        
        
         
       
    }//GEN-LAST:event_resetarActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
       
      
        
        Double valorDesconto = valorTotal*0.80;
        
       
        lblValorTotal.setText(valorDesconto.toString());
        lblSemDesconto.setText(valorTotal.toString());
    }//GEN-LAST:event_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoInterestelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoInterestelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoInterestelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoInterestelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoInterestelar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jupiter;
    private javax.swing.JLabel lblOpcaoDois;
    private javax.swing.JLabel lblOpcaoTres;
    private javax.swing.JLabel lblOpcaoUm;
    private javax.swing.JLabel lblSemDesconto;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JButton marte;
    private javax.swing.JButton netuno;
    private javax.swing.JButton resetar;
    private javax.swing.JButton saturno;
    private javax.swing.JButton terra;
    private javax.swing.JLabel txtTextoPrincipal;
    private javax.swing.JButton venus;
    // End of variables declaration//GEN-END:variables
}
